---
apiVersion: v1
kind: Namespace
metadata:
    name: influxdb

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-cm
  namespace: influxdb
data:
  INFLUXDB_INIT_MODE: 'setup'
  INFLUXDB_INIT_ORG: 'yungsem'
  INFLUXDB_INIT_BUCKET: 'default-bucket'
  INFLUXDB_INIT_USERNAME: 'root'
  INFLUXDB_INIT_PASSWORD: 'root123456'

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: influxdb
  name: influxdb
  namespace: influxdb
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: influxdb
  serviceName: influxdb-svc
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - env:
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: INFLUXDB_INIT_USERNAME
                  name: influxdb-cm
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: INFLUXDB_INIT_PASSWORD
                  name: influxdb-cm
            - name: DOCKER_INFLUXDB_INIT_ORG
              valueFrom:
                configMapKeyRef:
                  key: INFLUXDB_INIT_ORG
                  name: influxdb-cm
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              valueFrom:
                configMapKeyRef:
                  key: INFLUXDB_INIT_BUCKET
                  name: influxdb-cm
            - name: DOCKER_INFLUXDB_INIT_MODE
              valueFrom:
                configMapKeyRef:
                  key: INFLUXDB_INIT_MODE
                  name: influxdb-cm
          image: 'influxdb:2.0.6'
          imagePullPolicy: IfNotPresent
          name: influxdb
          ports:
            - containerPort: 8086
              name: influxdb
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/influxdb2
              name: influxdb-data-vol
            - mountPath: /etc/influxdb2
              name: influxdb-config-vol
            - mountPath: /etc/localtime
              name: localtime-vol
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: influxdb-data-vol
          hostPath:
            path: /k8s/influxdb/data
            type: DirectoryOrCreate
        - name: influxdb-config-vol
          hostPath:
            path: /k8s/influxdb/config
            type: DirectoryOrCreate
        - name: localtime-vol
          hostPath:
            path: /etc/localtime
            type: ''
          
  updateStrategy:
    type: RollingUpdate

---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
  namespace: influxdb
spec:
  ports:
    - name: influxdb
      port: 8086
      protocol: TCP
      targetPort: 8086
      nodePort: 31000
  selector:
    app: influxdb
  sessionAffinity: None
  type: NodePort